// Filter constants for internships and other features

const CATEGORY_ARRAY = [
	{
		name: ".NET Development",
		label: ".NET Development",
	},
	{
		name: "3D Printing",
		label: "3D Printing",
	},
	{
		name: "AI Agent Development",
		label: "AI Agent Development",
	},
	{
		name: "ASP.Net",
		label: "ASP.NET Development",
	},
	{
		name: "Accounts",
		label: "Accounts",
	},
	{
		name: "Acting",
		label: "Acting",
	},
	{
		name: "Aerospace",
		label: "Aerospace Engineering",
	},
	{
		name: "Agriculture and Food Engineering",
		label: "Agriculture & Food Engineering",
	},
	{
		name: "Analytics",
		label: "Analytics",
	},
	{
		name: "Anchoring",
		label: "Anchoring",
	},
	{
		name: "Android App Development",
		label: "Android App Development",
	},
	{
		name: "Angular.js Development",
		label: "Angular.js Development",
	},
	{
		name: "Animation",
		label: "Animation",
	},
	{
		name: "Architecture",
		label: "Architecture",
	},
	{
		name: "Artificial Intelligence (AI)",
		label: "Artificial Intelligence (AI)",
	},
	{
		name: "Audio Making/Editing",
		label: "Audio Making/Editing",
	},
	{
		name: "Auditing",
		label: "Auditing",
	},
	{
		name: "Automobile Engineering",
		label: "Automobile Engineering",
	},
	{
		name: "Backend Development",
		label: "Backend Development",
	},
	{
		name: "Bank",
		label: "Bank",
	},
	{
		name: "Big Data",
		label: "Big Data",
	},
	{
		name: "Bioinformatics",
		label: "Bioinformatics",
	},
	{
		name: "Biology",
		label: "Biology",
	},
	{
		name: "Biotech",
		label: "Biotechnology Engineering",
	},
	{
		name: "Blockchain Development",
		label: "Blockchain Development",
	},
	{
		name: "Blogging",
		label: "Blogging",
	},
	{
		name: "Brand Management",
		label: "Brand Management",
	},
	{
		name: "Business Development",
		label: "Business Development",
	},
	{
		name: "MBA",
		label: "Business/MBA",
	},
	{
		name: "CA Articleship",
		label: "CA Articleship",
	},
	{
		name: "CAD Design",
		label: "CAD Design",
	},
	{
		name: "CS Articleship",
		label: "CS Articleship",
	},
	{
		name: "Campus Ambassador",
		label: "Campus Ambassador",
	},
	{
		name: "Chartered Accountancy (CA)",
		label: "Chartered Accountancy (CA)",
	},
	{
		name: "Chemical",
		label: "Chemical Engineering",
	},
	{
		name: "Chemistry",
		label: "Chemistry",
	},
	{
		name: "Cinematography",
		label: "Cinematography",
	},
	{
		name: "Civil",
		label: "Civil Engineering",
	},
	{
		name: "Client Servicing",
		label: "Client Servicing",
	},
	{
		name: "Cloud Computing",
		label: "Cloud Computing",
	},
	{
		name: "Commerce",
		label: "Commerce",
	},
	{
		name: "Company Secretary (CS)",
		label: "Company Secretary (CS)",
	},
	{
		name: "Computer Science",
		label: "Computer Science",
	},
	{
		name: "Computer Vision",
		label: "Computer Vision",
	},
	{
		name: "Content Writing",
		label: "Content Writing",
	},
	{
		name: "Copywriting",
		label: "Copywriting",
	},
	{
		name: "Creative Design",
		label: "Creative Design",
	},
	{
		name: "Creative Writing",
		label: "Creative Writing",
	},
	{
		name: "Culinary Arts",
		label: "Culinary Arts",
	},
	{
		name: "Customer Service",
		label: "Customer Service",
	},
	{
		name: "Cyber Security",
		label: "Cyber Security",
	},
	{
		name: "Data Entry",
		label: "Data Entry",
	},
	{
		name: "Data Science",
		label: "Data Science",
	},
	{
		name: "Database Building",
		label: "Database Building",
	},
	{
		name: "Design",
		label: "Design",
	},
	{
		name: "Dietetics/Nutrition",
		label: "Dietetics/Nutrition",
	},
	{
		name: "Digital Marketing",
		label: "Digital Marketing",
	},
	{
		name: "E-commerce",
		label: "E-commerce",
	},
	{
		name: "Editorial",
		label: "Editorial",
	},
	{
		name: "Electric Vehicle",
		label: "Electric Vehicle",
	},
	{
		name: "Electrical",
		label: "Electrical Engineering",
	},
	{
		name: "Electronics",
		label: "Electronics Engineering",
	},
	{
		name: "Embedded Systems",
		label: "Embedded Systems",
	},
	{
		name: "Energy Science and Engineering",
		label: "Energy Science & Engineering",
	},
	{
		name: "Engineering",
		label: "Engineering",
	},
	{
		name: "Engineering Design",
		label: "Engineering Design",
	},
	{
		name: "Engineering Physics",
		label: "Engineering Physics",
	},
	{
		name: "Environmental Sciences",
		label: "Environmental Sciences",
	},
	{
		name: "Event Management",
		label: "Event Management",
	},
	{
		name: "Facebook Marketing",
		label: "Facebook Marketing",
	},
	{
		name: "Fashion Design",
		label: "Fashion Design",
	},
	{
		name: "Film Making",
		label: "Film Making",
	},
	{
		name: "Finance",
		label: "Finance",
	},
	{
		name: "Flutter Development",
		label: "Flutter Development",
	},
	{
		name: "Front End Development",
		label: "Front End Development",
	},
	{
		name: "Full Stack Development",
		label: "Full Stack Development",
	},
	{
		name: "Fundraising",
		label: "Fundraising",
	},
	{
		name: "Game Design",
		label: "Game Design",
	},
	{
		name: "Game Development",
		label: "Game Development",
	},
	{
		name: "General Management",
		label: "General Management",
	},
	{
		name: "Government",
		label: "Government",
	},
	{
		name: "Graphic Design",
		label: "Graphic Design",
	},
	{
		name: "Hospitality",
		label: "Hospitality",
	},
	{
		name: "Hotel Management",
		label: "Hotel Management",
	},
	{
		name: "HR",
		label: "Human Resources (HR)",
	},
	{
		name: "Humanities",
		label: "Humanities",
	},
	{
		name: "Image Processing",
		label: "Image Processing",
	},
	{
		name: "Industrial and Production Engineering",
		label: "Industrial & Production Engineering",
	},
	{
		name: "Industrial Design",
		label: "Industrial Design",
	},
	{
		name: "Information Technology",
		label: "Information Technology",
	},
	{
		name: "Instrumentation and Control Engineering",
		label: "Instrumentation & Control Engineering",
	},
	{
		name: "Interior Design",
		label: "Interior Design",
	},
	{
		name: "International",
		label: "International",
	},
	{
		name: "Internet of Things (IoT)",
		label: "Internet of Things (IoT)",
	},
	{
		name: "Java",
		label: "Java Development",
	},
	{
		name: "Javascript Development",
		label: "Javascript Development",
	},
	{
		name: "Journalism",
		label: "Journalism",
	},
	{
		name: "Law",
		label: "Law",
	},
	{
		name: "Legal Research",
		label: "Legal Research",
	},
	{
		name: "MLOps Engineering",
		label: "MLOps Engineering",
	},
	{
		name: "Machine Learning",
		label: "Machine Learning",
	},
	{
		name: "Manufacturing Engineering",
		label: "Manufacturing Engineering",
	},
	{
		name: "Market/Business Research",
		label: "Market/Business Research",
	},
	{
		name: "Marketing",
		label: "Marketing",
	},
	{
		name: "Material Science",
		label: "Material Science",
	},
	{
		name: "Mathematics",
		label: "Mathematics",
	},
	{
		name: "Mathematics and Computing",
		label: "Mathematics & Computing",
	},
	{
		name: "Mechanical",
		label: "Mechanical Engineering",
	},
	{
		name: "Mechatronics",
		label: "Mechatronics",
	},
	{
		name: "Media",
		label: "Media",
	},
	{
		name: "Medicine",
		label: "Medicine",
	},
	{
		name: "Merchandise Design",
		label: "Merchandise Design",
	},
	{
		name: "Mobile App Development",
		label: "Mobile App Development",
	},
	{
		name: "Motion Graphics",
		label: "Motion Graphics",
	},
	{
		name: "Music",
		label: "Music",
	},
	{
		name: "NGO",
		label: "NGO",
	},
	{
		name: "Natural Language Processing (NLP)",
		label: "Natural Language Processing (NLP)",
	},
	{
		name: "Naval and Ocean",
		label: "Naval Architecture and Ocean Engineeering",
	},
	{
		name: "Network Engineering",
		label: "Network Engineering",
	},
	{
		name: "Node.js Development",
		label: "Node.js Development",
	},
	{
		name: "Operations",
		label: "Operations",
	},
	{
		name: "PHP Development",
		label: "PHP Development",
	},
	{
		name: "Pharmaceutical",
		label: "Pharmaceutical",
	},
	{
		name: "Photography",
		label: "Photography",
	},
	{
		name: "Physics",
		label: "Physics",
	},
	{
		name: "Political/Economics/Policy Research",
		label: "Political/Economics/Policy Research",
	},
	{
		name: "Product",
		label: "Product Management",
	},
	{
		name: "Programming",
		label: "Programming",
	},
	{
		name: "Project Management",
		label: "Project Management",
	},
	{
		name: "Prompt Engineering",
		label: "Prompt Engineering",
	},
	{
		name: "Proofreading",
		label: "Proofreading",
	},
	{
		name: "Psychology",
		label: "Psychology",
	},
	{
		name: "PR",
		label: "Public Relations (PR)",
	},
	{
		name: "Python/Django",
		label: "Python/Django Development",
	},
	{
		name: "Quality Analyst",
		label: "Quality Analyst",
	},
	{
		name: "Recruitment",
		label: "Recruitment",
	},
	{
		name: "Robotics",
		label: "Robotics",
	},
	{
		name: "Ruby on Rails",
		label: "Ruby on Rails",
	},
	{
		name: "Sales",
		label: "Sales",
	},
	{
		name: "Science",
		label: "Science",
	},
	{
		name: "Search Engine Optimization (SEO)",
		label: "Search Engine Optimization (SEO)",
	},
	{
		name: "Social Media Marketing",
		label: "Social Media Marketing",
	},
	{
		name: "Social Work",
		label: "Social Work",
	},
	{
		name: "Software Development",
		label: "Software Development",
	},
	{
		name: "Software Testing",
		label: "Software Testing",
	},
	{
		name: "Sports",
		label: "Sports",
	},
	{
		name: "Statistics",
		label: "Statistics",
	},
	{
		name: "Stock/Market Trading",
		label: "Stock/Market Trading",
	},
	{
		name: "Strategy",
		label: "Strategy",
	},
	{
		name: "Subject Matter Expert (SME)",
		label: "Subject Matter Expert (SME)",
	},
	{
		name: "Supply Chain Management (SCM)",
		label: "Supply Chain Management (SCM)",
	},
	{
		name: "Talent Acquisition",
		label: "Talent Acquisition",
	},
	{
		name: "Teaching",
		label: "Teaching",
	},
	{
		name: "Telecalling",
		label: "Telecalling",
	},
	{
		name: "Transcription",
		label: "Transcription",
	},
	{
		name: "Translation",
		label: "Translation",
	},
	{
		name: "Travel and Tourism",
		label: "Travel & Tourism",
	},
	{
		name: "UI/UX",
		label: "UI/UX Design",
	},
	{
		name: "Video Making/Editing",
		label: "Video Making/Editing",
	},
	{
		name: "Videography",
		label: "Videography",
	},
	{
		name: "Volunteering",
		label: "Volunteering",
	},
	{
		name: "Web Development",
		label: "Web Development",
	},
	{
		name: "Wordpress Development",
		label: "Wordpress Development",
	},
	{
		name: "iOS App Development",
		label: "iOS App Development",
	},
];

const CITY_ARRAY = [
	"Abohar",
	"Agra",
	"Agroha",
	"Ahmedabad",
	"Ahmednagar",
	"Ajmer",
	"Akola",
	"Akurdi",
	"Alappuzha",
	"Aligarh",
	"Allahabad",
	"Alwal",
	"Alwar",
	"Amalapuram",
	"Amaravati",
	"Ambala",
	"Ambala Cantt",
	"Ambala Division",
	"Ambarnath",
	"Ambernath",
	"Amboa",
	"Ambota",
	"Ameerpet",
	"Amravati",
	"Amritsar",
	"Amroha",
	"Anand",
	"Anantapuram",
	"Andhra Pradesh",
	"Andra",
	"Anekal",
	"Angul",
	"Anjuna",
	"Anu",
	"Aradi Socorro",
	"Arya Nagar",
	"Asrawan",
	"Assam",
	"Atal Nagar",
	"Auckland",
	"Aundh",
	"Aurangabad",
	"Aurangabad Division",
	"Avadi",
	"Awantipora",
	"Azamgarh",
	"Badarpur",
	"Badhawar",
	"Badi Dhar",
	"Badlapur",
	"Bagalkote",
	"Bagalur",
	"Bagla",
	"Bagru",
	"Bahadurgarh",
	"Balanagar",
	"Balasore",
	"Balh",
	"Ballabhgarh",
	"Balu",
	"Bandipore",
	"Bandra",
	"Bangalore",
	"Bangarapet",
	"Banikhet",
	"Bapatla",
	"Bara",
	"Baramati",
	"Baramula",
	"Barara",
	"Barbil",
	"Bardoli",
	"Bareilly",
	"Barnala",
	"Barotiwala",
	"Barsat",
	"Baruhi",
	"Basantpur",
	"Batheri",
	"Bathinda",
	"Bawal",
	"Bazpur",
	"Beed",
	"Begumpet",
	"Belagavi",
	"Belapur",
	"Belgaum Division",
	"Bellary",
	"Berhampore",
	"Berhampura",
	"Bettiah",
	"Bhagalpur",
	"Bhaini",
	"Bharatpur",
	"Bharmour",
	"Bharuch",
	"Bhavnagar",
	"Bhilai",
	"Bhilwara",
	"Bhimtal",
	"Bhiwadi",
	"Bhiwandi",
	"Bhiwani",
	"Bhopal",
	"Bhopalgarh",
	"Bhoranj",
	"Bhubaneswar",
	"Bhutan",
	"Biana",
	"Bidar",
	"Bihar",
	"Bijhri",
	"Bijnor",
	"Bikaner",
	"Bir",
	"Birbhum",
	"Bommasandra",
	"Bulandshahar",
	"Bulandshahr",
	"Buldhana",
	"Calangute",
	"Candolim",
	"Chakan",
	"Chakrata",
	"Chalet",
	"Chamarajanagar",
	"Chamba",
	"Chamba Sub-District",
	"Chambhurdi",
	"Chandannagar",
	"Chandigarh",
	"Chata",
	"Chauli",
	"Chennai",
	"Chhaproh",
	"Chhatrapati Sambhajinagar",
	"Chhatrapati Sambhajinagar (Aurangabad)",
	"Chhatri",
	"Chhattisgarh",
	"Chichwad",
	"Chikhli",
	"Chinchwad",
	"Chirao",
	"Chittoor",
	"Choli",
	"Chotpur",
	"Chouk",
	"Chowari",
	"Chuli Bagriyan",
	"Cochin",
	"Coimbatore",
	"Coimbatore North",
	"Coimbatore South",
	"Colachel",
	"Cuddapah",
	"Cuttack",
	"Dadu",
	"Dahisar",
	"Dakshina Kannada",
	"Daman",
	"Daman And Diu",
	"Darjeeling",
	"Dehar",
	"Dehradun",
	"Dehradun Sub-District",
	"Delhi",
	"Deoghar",
	"Deori",
	"Devipatan Division",
	"Dewas",
	"Dhaban",
	"Dhanaulti",
	"Dhanaura",
	"Dhanbad",
	"Dhansura",
	"Dhar",
	"Dharampur",
	"Dharmapuri",
	"Dharmpur",
	"Dharwad",
	"Dhenkanal",
	"Dindigul",
	"District D'Ernakulam",
	"Doda",
	"Dombivli",
	"Draksharamam",
	"Dubai",
	"Dumka",
	"Durg",
	"Durgapur West",
	"Dwarka",
	"E",
	"East Godavari",
	"East Singhbhum",
	"England",
	"Ernakulam",
	"Erode",
	"Etah",
	"Etawah",
	"Faridabad",
	"Fatehabad",
	"Fatehgarh Sahib",
	"Fatehpur",
	"Fazilka",
	"Ferozpur",
	"Firozabad",
	"Gadarpur",
	"Gagret",
	"Gandhinagar",
	"Garhwal Division",
	"Gauna",
	"Gautam Buddh Nagar",
	"Gautam Buddha Nagar",
	"Gawali",
	"Gaya",
	"Gazipur",
	"Ghaziabad",
	"Ghaziabad Sub-District",
	"Giridih",
	"Goa",
	"Goa Velha",
	"Godda",
	"Gohana",
	"Gonda",
	"Gopalpur",
	"Gorakhpur",
	"Gorkhapur",
	"Greater London",
	"Greater Noida",
	"Greater Noida West",
	"Gujarat",
	"Gujrat",
	"Gulbarga",
	"Guntur",
	"Guraru",
	"Gurgaon",
	"Gurgaon Division",
	"Guwahati",
	"Gwalior",
	"Haldwani",
	"Halol",
	"Hamirpur",
	"Hansi",
	"Hapur",
	"Haralur",
	"Haridwar",
	"Haroli",
	"Haryana",
	"Haveri",
	"Hebbal",
	"Himachal Pradesh",
	"Himmatnagar",
	"Hinjawadi",
	"Hisar",
	"Hisar Division",
	"Holi",
	"Hooghly",
	"Hoshiarpur",
	"Hosur",
	"Howrah",
	"Hyderabad",
	"Idukki",
	"Indiranagara",
	"Indore",
	"Indore Division",
	"Jabalpur",
	"Jabhala",
	"Jaipur",
	"Jajpur",
	"Jalandhar",
	"Jalgaon",
	"Jalna",
	"Jalpaiguri",
	"Jambhe",
	"Jammu",
	"Jammu & Kashmir",
	"Jammu And Kashmir",
	"Jamshedpur",
	"Jaspur",
	"Jhajjar",
	"Jhansi",
	"Jhansi Khas",
	"Jhansi Rly. Settl",
	"Jhargram",
	"Jharkhand",
	"Jhiri",
	"Jhunjhunu",
	"Jind",
	"Joda",
	"Jodhpur",
	"Joh",
	"Jol",
	"Jowai",
	"Kabrel",
	"Kadapa",
	"Kadi",
	"Kaithal",
	"Kakinada",
	"Kalamboli",
	"Kalirawan",
	"Kalka",
	"Kalol",
	"Kalyan",
	"Kamrup",
	"Kamshet",
	"Kanakapura Rural",
	"Kanchipuram",
	"Kangra",
	"Kangra Division",
	"Kanniyakumari",
	"Kannur",
	"Kanpur",
	"Kanpur Dehat",
	"Kanyakumari",
	"Karad",
	"Karimnagar",
	"Karnal",
	"Karnal Division",
	"Karnataka",
	"Karsog",
	"Karur",
	"Kasaragod",
	"Kashipur",
	"Kasol",
	"Kathua",
	"Kattigenahalli",
	"Kaushambi",
	"Kayamkulam",
	"Kendujhar",
	"Keonjhar",
	"Kerala",
	"Kerala Estate",
	"Keralapuram",
	"Keralassery",
	"Khagaria",
	"Khammam",
	"Khandwa",
	"Khanpur",
	"Kharadi",
	"Kharar",
	"Khargone",
	"Kharian",
	"Kheda",
	"Khordha",
	"Kichha",
	"Kishtwar",
	"Kochi",
	"Kochi Prefecture",
	"Kodad",
	"Kohla",
	"Kolar",
	"Kolhapur",
	"Kolkata",
	"Kollam",
	"Kondapur",
	"Konkan Division",
	"Koppal",
	"Koramangala",
	"Kota",
	"Kothagudem",
	"Kothamangalam",
	"Kothi",
	"Kott",
	"Kottayam",
	"Kozhikode",
	"Krishna",
	"Krishnagar",
	"Krishnagiri",
	"Kuddi",
	"Kufri",
	"Kukatpalle",
	"Kullu",
	"Kupwara",
	"Kupwara Sub-District",
	"Kurla",
	"Kurnool",
	"Kurukshetra",
	"Kushtagi",
	"Ladakh",
	"Ladwi",
	"Lahaul And Spiti",
	"Lakhimpur Kheri",
	"Lakhisarai",
	"Lambloo",
	"LB Nagar",
	"Leh",
	"Leh (Ladakh)",
	"Lingampally",
	"Lohara",
	"Lonavala",
	"London",
	"Lucknow",
	"Ludhiana",
	"Ludhiani",
	"Madhapur",
	"Madhya Pradesh",
	"Madurai",
	"Mahabubnagar",
	"Maharashtra",
	"Mahbubnagar",
	"Maheshtala",
	"Mahua",
	"Mainpuri",
	"Malappuram",
	"Malda",
	"Malviya Nagar",
	"Manali",
	"Mandapeta",
	"Mandar",
	"Mandi",
	"Mandi Division",
	"Mandi Gobindgarh",
	"Mandoli",
	"Mandya",
	"Manesar",
	"Mangalore",
	"Manipal",
	"Mansa",
	"Mapusa",
	"Margao",
	"Mathura",
	"Mavelikara",
	"Mawa Kaholan",
	"Mazgaon",
	"Medak",
	"Medchal District",
	"Meerut",
	"Meerut Division",
	"Meghalaya",
	"Mehsana",
	"Mettur",
	"Mira Bhayandar",
	"Mira Road",
	"Mirzapur",
	"Mirzapur-cum-Vindhyachal",
	"Modinagar",
	"Mohali",
	"Moinabad",
	"Moradabad",
	"Morshi",
	"Mount Abu",
	"Muktsar",
	"Mullana",
	"Mumbai",
	"Mummidivaram",
	"Munger Division",
	"Muradnagar",
	"Murshidabad",
	"Mussoorie",
	"Mysore Division",
	"Mysuru",
	"Nadaun",
	"Nadiad",
	"Nagothane",
	"Nagpur",
	"Nainital",
	"Nakroh",
	"Nala Sopara",
	"Nalagarh",
	"Nalgonda",
	"Namakkal",
	"Nanded",
	"Nandpur",
	"Narendra Nagar",
	"Narendrapur",
	"Nashik",
	"Navi Mumbai",
	"Navrangpura",
	"Navsari",
	"Nayagarh",
	"Neemrana",
	"Nellore",
	"Nera",
	"New Delhi",
	"Noida",
	"North",
	"North 24 Parganas",
	"North Chotanagpur Division",
	"North Dumdum",
	"North Goa",
	"Northern Division",
	"Odisha",
	"Ontario",
	"Osmanabad",
	"Palakkad",
	"Palghar",
	"Pali",
	"Panaji",
	"Panchgani",
	"Panchkula",
	"Panchmahal",
	"Panipat",
	"Panjim",
	"Panjlasa",
	"Panoh",
	"Pantnagar",
	"Pashchim Champaran",
	"Patan",
	"Patera",
	"Pathanamthitta",
	"Patiala",
	"Patna",
	"Penha De França",
	"Perinthalmanna",
	"Phulnakhara",
	"Pilani",
	"Pilerne",
	"Pimpri-Chinchwad",
	"Pinjore",
	"Pitampura",
	"Pondicherry",
	"Pratapgarh",
	"Presidency Division",
	"Pulwama",
	"Punalur",
	"Pune",
	"Pune Division",
	"Punewadi",
	"Punj",
	"Punjab",
	"Puri",
	"Purulia",
	"Rai Durg",
	"Raichur",
	"Raigad",
	"Raigarh",
	"Raipur",
	"Rajahmundry",
	"Rajamahendravaram",
	"Rajasthan",
	"Rajauri",
	"Rajkot",
	"Rajpura",
	"Ram Nagar",
	"Ramanagara",
	"Ramban",
	"Ramgarh",
	"Ramnagar",
	"Rampurhat",
	"Ranchi",
	"Ranga Reddy",
	"Ranibennur Rural",
	"Ratlam",
	"Rayachoty",
	"Reasi",
	"Rewa",
	"Rewari",
	"Rishikesh",
	"Rohtak",
	"Roorkee",
	"Rora Baliwal",
	"Rourkela",
	"Rudrapur",
	"Rupnagar",
	"Sabarkatha",
	"Sadyana",
	"Safidon",
	"Sagar",
	"Saharanpur",
	"Sahibzada Ajit Singh Nagar",
	"Sainsowal",
	"Salem",
	"Saligao",
	"Salwan",
	"Samastipur",
	"Samba",
	"Samba Sub-District",
	"Sambalpur",
	"Sanand",
	"Sangareddy",
	"Sangrur",
	"Sanjan",
	"Sanoli",
	"Sant Kabir Nagar",
	"Sari",
	"Sarjapur",
	"Sarkhej-Okaf",
	"Sarol",
	"Satara",
	"Satna",
	"Secunderabad",
	"Shahjahanpur",
	"Shamli",
	"Shikohabad",
	"Shimla",
	"Shimla Division",
	"Sikar",
	"Siliguri",
	"Sion Koliwada",
	"Sirmaur",
	"Sirohi",
	"Sitamarhi",
	"Solan",
	"Solapur",
	"Sonarpur",
	"Sonbhadra",
	"Sonepat",
	"Sonipat",
	"South",
	"South 24 Parganas",
	"South East",
	"South Goa",
	"South Mumbai",
	"Sri Ganganagar",
	"Srinagar",
	"Sudhar",
	"Sujanpur Tira",
	"Sukher",
	"Sundargarh",
	"Sunehra",
	"Sungal",
	"Surat",
	"Surendranagar",
	"Suryapet",
	"Tadipatri",
	"Tallarevu",
	"Taloja, Dist Raigad",
	"Tamil Nadu",
	"Tehri Garhwal",
	"Telangana",
	"Thana",
	"Thane",
	"Thanjavur",
	"Thiruvananthapuram",
	"Thiruvankulam",
	"Thoothukudi",
	"Thrissur",
	"Tibbi",
	"Tikri",
	"Tirchy",
	"Tiruchi",
	"Tiruchirappalli",
	"Tirunelveli",
	"Tirupati",
	"Tiruppur",
	"Tiruvallur",
	"Tiswadi",
	"Titwala",
	"Toronto",
	"Toronto Division",
	"Tumkur",
	"Tundla",
	"Turbhe",
	"Udaipur",
	"Udaipuriya",
	"Udham Singh Nagar",
	"Udhampur",
	"Udupi",
	"Ujjain",
	"Ukhali",
	"Ulhasnagar",
	"Una",
	"Unnao",
	"Uppal",
	"Uttar Pradesh",
	"Uttar Pranpur",
	"Uttara Kannada",
	"Uttarakhand",
	"Uttarkashi",
	"Uttarpara Kotrung",
	"Vadodara",
	"Vaishali",
	"Vallabh Vidhyanagar",
	"Valsad",
	"Vapi",
	"Varanasi",
	"Vasai",
	"Vasai-Virar",
	"Vashi",
	"Vashi Navi Mumbai",
	"Vellore",
	"Velur",
	"Vijayawada",
	"Vikasnagar",
	"Villupuram",
	"Virar",
	"Visakhapatnam",
	"Vishakhapatnam",
	"Visnagar",
	"Vizianagaram",
	"Vrindavan",
	"Wadala",
	"Wagholi",
	"Wakad",
	"Wakadi",
	"Warangal",
	"Wayanad",
	"West",
	"West Bengal",
	"West Godavari",
	"West Jaintia Hills",
	"West Medinipur",
	"West Patel Nagar",
	"West Singhbhum",
	"Yamuna Nagar",
	"Yanam",
	"Yavatmal",
	"Yelahanka",
	"Zirakpur",
];

// Indian States and Union Territories
const STATE_ARRAY = [
	"Andhra Pradesh",
	"Arunachal Pradesh",
	"Assam",
	"Bihar",
	"Chhattisgarh",
	"Goa",
	"Gujarat",
	"Haryana",
	"Himachal Pradesh",
	"Jammu and Kashmir",
	"Jharkhand",
	"Karnataka",
	"Kerala",
	"Ladakh",
	"Madhya Pradesh",
	"Maharashtra",
	"Manipur",
	"Meghalaya",
	"Mizoram",
	"Nagaland",
	"Odisha",
	"Punjab",
	"Rajasthan",
	"Sikkim",
	"Tamil Nadu",
	"Telangana",
	"Tripura",
	"Uttarakhand",
	"Uttar Pradesh",
	"West Bengal",
	// Union Territories
	"Andaman and Nicobar Islands",
	"Chandigarh",
	"Dadra and Nagar Haveli and Daman and Diu",
	"Delhi",
	"Lakshadweep",
	"Puducherry",
];

module.exports = {
	CATEGORY_ARRAY,
	CITY_ARRAY,
	STATE_ARRAY,
};
